# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build API

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/PlanManagement.sln 
    - name: Build
      run: dotnet build --no-restore ./src/PlanManagement.sln 
#    - name: Test
#      run: dotnet test --no-build --verbosity normal ./src/api-test/api-test.csproj 
