name: Publish to DEV Server

on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish to DEV Server'

permissions:
  contents: read

jobs:
  publish:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore Dependencies API 
        run: dotnet restore ./src/PlanManagement.sln 
      - name: Build API
        run: dotnet build --no-restore ./src/PlanManagement.sln 

      - name: Publish API
        run: dotnet publish -c Release ./src/PlanManagement.sln -o C:\inetpub\sites\dev

      - name: Copy Web.Config
        run: copy web.config C:\inetpub\sites\dev\web.config

      - name: Copy appsettings.json
        run: copy appsettings.json C:\inetpub\sites\dev\appsettings.json

      - name: Build UI
        run: (cd ./src/ui/src/) -and (npm install) -and (npm run build)
      
      - name: Copy UI to wwwroot
        uses: actions/upload-artifact@v3
        with:
          name: UI
          path: C:\inetpub\sites\dev\wwwroot


      