name: Build & deploy to FTP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore Dependencies API 
        run: dotnet restore ./src/PlanManagement.sln 
      - name: Build API
        run: dotnet build --no-restore ./src/PlanManagement.sln 

      - name: Publish API
        run: dotnet publish -c Release ./src/PlanManagement.sln -o ${{env.DOTNET_ROOT}}/raj-host

      - name: Upload API Artifact
        uses: actions/upload-artifact@v3
        with:
          name: API
          path: ${{env.DOTNET_ROOT}}/raj-host

      - name: Build UI
        run: cd ./src/ui/src/ && npm install && npm run build
      
      - name: Upload API Artifact
        uses: actions/upload-artifact@v3
        with:
          name: UI
          path: ${{env.DOTNET_ROOT}}/raj-host/wwwroot

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: API-UI
          path: release.zip

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'DEV'
      url: ${{ steps.deploy-to-ftp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: .net-app        

    - name: Deploy to FTP
      id: deploy-to-ftp
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ vars.FTP_LOCATION }}
        username: ${{ vars.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
