name: Build $ deploy to FTP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore Dependencies
        run: dotnet restore ./src/PlanManagement.sln 
      - name: Build
        run: dotnet build --no-restore ./src/PlanManagement.sln 

      - name: dotnet publish
        run: dotnet publish -c Release ./src/PlanManagement.sln -o ${{env.DOTNET_ROOT}}/raj-host

      - name: Upload Artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/raj-host

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'DEV'
      url: ${{ steps.deploy-to-ftp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: .net-app        

    - name: Deploy to FTP
      id: deploy-to-ftp
      uses: azure/webapps-deploy@v2
      with:
        server: ${{ vars.FTP_LOCATION }}
        username: ${{ vars.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
