name: API Deploy to DEV

on:
  workflow_dispatch:
    inputs:
      publish-api:
        description: 'Note'
env:
  CI: false
  REACT_APP_API_URL: https://65.0.190.66/api

permissions:
  contents: read

jobs:
  publish-api:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      - name: Replace appsettings.json
        run: copy appsettings.json ./src/raj-host/appsettings.json

      - name: Run DB Migration
        run: |
          dotnet tool install --global dotnet-ef
          dotnet tool restore
          dotnet ef database update --project ./src/ilab-authentication/ilab-authentication.csproj --startup-project ./src/raj-host/raj-host.csproj --context IlabAuthentication.Data.AuthenticationDbContext
          dotnet ef database update --project ./src/raj-api/raj-api.csproj --startup-project ./src/raj-host/raj-host.csproj --context RajApi.Data.ApplicationDbContext

      - name: Restore Dependencies API 
        run: dotnet restore ./src/PlanManagement.sln 

      - name: Build API
        run: dotnet build --no-restore ./src/PlanManagement.sln 

      - name: iisreset /stop
        run: iisreset /stop

      - name: Publish API
        run: dotnet publish -c Release ./src/PlanManagement.sln -o C:\inetpub\sites\dev

      - name: Copy Web.Config
        run: copy web.config C:\inetpub\sites\dev\web.config
      
      - name: iisreset /start
        run: iisreset /start

    
  
      